name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install ALSA Development Libraries
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o blue-goblin_${{ github.ref_name }}.exe

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o blue-goblin_${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          artifacts: |
            blue-goblin_${{ github.ref_name }}.exe
            blue-goblin_${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}